### PR TITLE
Fix underflowing xkey gauges

### LINKED ISSUE #157: xkey_test12 fails, branch 6.4 on 32 bit
I started test building varnish-modules branch 6.4 on misc arches yesterday.

xkey_test12 fails on epel-6-i386. Log attached.

Ingvar

### LINKED ISSUE #159: XKEY.g_ochead_bytes underflows
Over time while Varnish is running, the XKEY.g_ochead_bytes counter sometimes underflows.

image

In this chart, the far-right value is 18446744073708882000, which should be -669616 except that the counter is an unsigned 64-bit integer.

Note that g_ochead_bytes is a DEBUG level counter. To see it in varnish stat you need to press `v` a couple times.

### PR DESCRIPTION
**Pull request by xordspar0**
Fixes #159 
Fixes #157

### CODE REVIEW

**Comment by xordspar0** [comment]
Our test looks good!

image

File: src/vmod_xkey.c [hunk 1]
```diff
@@ -220,6 +220,8 @@ static struct xkey_oc *
 xkey_oc_new(void)
 {
 	struct xkey_oc *oc;
+	vsc->g_oc_bytes += sizeof(*oc);
```
Comment (gquintard) [inline src/vmod_xkey.c]: is it the only code change needed here? All others changes seem to shuffle things around without changing the logic

File: src/tests/xkey/test13.vtc [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+		if (req.http.xkey-purge) {
+			if (xkey.purge(req.http.xkey-purge) != 0) {
+				return (synth(200, "Purged"));
+			} else {
+				return (synth(404, "No key"));
+			}
+		}
+	}
+
+	sub vcl_backend_response {
```
Comment (gquintard) [inline src/tests/xkey/test13.vtc]: not needed? the default ttl is 2 minutes, which should be fine for this test?

File: src/tests/xkey/test13.vtc [hunk 3]
```diff
@@ -0,0 +1,118 @@
+varnishtest "Make many requests and purge them all"
+
+server s1 {
```
Comment (gquintard) [inline src/tests/xkey/test13.vtc]: I think you can get away with:

```
server s1 -repeat 11 {
  rxreq
  rxresp
}
```

(same thing for `c1`) and in the vcl:

```
sub vcl_backend_response {
  set beresp.http.xkey = bereq.xid;
}
```

File: src/vmod_xkey.c (hunk 1 above)
Comment (xordspar0) [reply src/vmod_xkey.c]: Yes. We wanted to put the increments and decrements in a consistent place for all the metrics.

File: src/tests/xkey/test13.vtc (hunk 3 above)
Comment (xordspar0) [reply src/tests/xkey/test13.vtc]: We need to fill up the xkey_pool, which requires deleting more than POOL_MAX xkeys. However...now that I think about it I don't think we need to fill up the pool. We just need one item to be in the pool to cause the bug we caused before.

1. Cache an item.
2. Purge it.
3. Cache another item, whose memory is taken from the pool.
4. Purge again.

The g_oc_bytes gauge would already underflow at this point. Our test would fail after step 3 because it would expect the gauge to increase and in the pre-patched version of the code it didn't do that.

**Comment by gquintard** [comment]
ok for me. Can we get some simpler tests and a squash before this goes in?

File: src/tests/xkey/test13.vtc (hunk 3 above)
Comment (xordspar0) [reply src/tests/xkey/test13.vtc]: That worked. We simplified the test and it still is able to catch our mistake. 👍

**Comment by xordspar0** [comment]
All review comments are addressed and the branch is squashed. Let us know if we need to make any more changes.

**Comment by gquintard** [comment]
sorry, could you add the vtc from https://github.com/varnish/varnish-modules/issues/157#issuecomment-600605683 to the test suite? maybe with a `_32bits` suffix?

Once done, all good to go

**Comment by xordspar0** [comment]
Is there a way to make a test only run on 32-bit hosts? I saw that there was a `feature 64bit` flag, but I didn't find a 32-bit equivalent. Also, just to clarify, test12 is 64-bit specific, but test13 is not architecture-specific.

**Comment by Dridi** [comment]
I wouldn't bother with a 32bit version of the test, skipping on non-essential arches is fine.

**Comment by gquintard** [comment]
@xordspar0 , you heard the man, all good on our side then. Ready on yours?

**Comment by xordspar0** [comment]
Yup, we're ready. 👍

**Comment by gquintard** [comment]
merged ,thanks a lot!
